[package]
name = "surrealdb_live_message"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.45", features = ["full", "macros", "rt-multi-thread"] }
tokio-stream = "0.1"
surrealdb = { version = "2.3.2", features = ["kv-mem"] }
# surrealdb = { git = "https://github.com/surrealdb/surrealdb", tag = "v2.0.0-beta.2", features = ["kv-mem"] }
futures = "0.3.31"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
miette = "7"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-graceful-shutdown = "0.16.0"
config = "0.15"
bollard = "0.19"
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "gzip",
] }

[dev-dependencies]
[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.30.1", default-features = false, features = ["signal"] }
