[package]
name = "surrealdb_live_message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.39.1", features = ["full", "macros", "rt-multi-thread"] }
tokio-stream = "0.1"
# surrealdb = { version = "1.5.3", features = ["kv-mem"] }
surrealdb = { git = "https://github.com/surrealdb/surrealdb", tag = "v2.0.0-alpha.2", features = ["kv-mem"] }
futures = "0.3.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
miette = "7"
tracing = "0.1"
tracing-subscriber = "0.3"
once_cell = "1.19"
tokio-graceful-shutdown = "0.15"
config = "0.14"
bollard = "0.16"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "gzip"] }


[dev-dependencies]
[target.'cfg(unix)'.dev-dependencies]
nix = { version = "0.29.0", default-features = false, features = ["signal"] }

[[test]]
name = "integration_test"
path = "test/integration_test.rs"

