environment = "development"

[logger]
level = "info"

[docker]
platform = "linux/x86_64"

[sdb]
host = "127.0.0.1"
port = 8000
image = "surrealdb/surrealdb"
tag = "v2.1.4"
container_name = "sdb_container"
namespace = "test"
database = "test"
username = "root"
password = "root"